FROM ubuntu:18.04

# install azure cli
RUN apt-get update && \
    apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg && \
    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null && \
    AZ_REPO=$(lsb_release -cs) && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list && \
    apt-get update && \
    apt-get install -y azure-cli

# install pwsh
RUN apt-get -y install wget software-properties-common && \
    wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    add-apt-repository universe && \
    apt-get install -y powershell

# install mssql-scripter
RUN apt-get -y install python python-pip && \
    pip install mssql-scripter

COPY stop-database.ps1 /stop-database.ps1

CMD ["pwsh" ,".\\stop-database.ps1", \
    "-ResourceGroupName", "", \
    "-DatabaseServerName", "", \
    "-DatabaseName", "", \
    "-AdminPassword", "", \ 
    "-AdminUsername", "", \ 
    "-StorageConnectionString", "\"<<connection string goes here>>\"", \ 
    "-StorageContainerName", ""]
